pipeline {
    agent any

    parameters {
        choice(
            name: 'DEPLOY_TARGET',
            choices: ['HOMELAB', 'VPS'],
            description: 'Select deployment target'
        )
    }

    environment {
        IMAGE_NAME = "kiranlintech/rudram"
        IMAGE_TAG  = "${BUILD_NUMBER}"

        HOMELAB_HOST = "192.168.5.9"
        VPS_HOST     = "213.210.37.106"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/kiranlintech/rudram.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh """
                    docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
                    docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest
                """
            }
        }

        stage('Push DockerHub') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub-creds',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {
                    sh '''
                        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

                        docker push ${IMAGE_NAME}:${IMAGE_TAG}
                        docker push ${IMAGE_NAME}:latest
                    '''
                }
            }
        }

        stage('Deploy') {
            steps {
                script {

                    def target = ""

                    if (params.DEPLOY_TARGET == "HOMELAB") {
                        target = "ubuntu@${HOMELAB_HOST}"
                    } else {
                        target = "ubuntu@${VPS_HOST}"
                    }

                    sh """
                    ssh ${target} '
                        docker pull ${IMAGE_NAME}:latest

                        docker stop rudram || true
                        docker rm rudram || true

                        docker run -d \
                            --name rudram \
                            -p 8082:8080 \
                            ${IMAGE_NAME}:latest
                    '
                    """
                }
            }
        }
    }
}
